name: Update Packages

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * *
  watch:
    types: started

env:
  BRANCH: master
  SCRIPT: package.sh

jobs:
  Update:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set Git Identity
      run : |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Update Packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x $SCRIPT
        git clone -b $BRANCH https://github.com/haiibo/openwrt-packages.git
        cd openwrt-packages
        git rm -r --cache * >/dev/null 2>&1
        rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
        $GITHUB_WORKSPACE/$SCRIPT
        echo "FILE_PATH=$PWD" >> $GITHUB_ENV

    - name: Upload Packages
      continue-on-error: true
      run: |
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $FILE_PATH
        [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $FILE_PATH
        cd $FILE_PATH
        git add .
        git commit -m "Update $(date +%Y-%m-%d" "%H:%M:%S)"
        git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/haiibo/openwrt-packages.git" HEAD:$BRANCH

    - name: Delete Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        retain_days: 1
        keep_minimum_runs: 3
